apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-pod
spec:
  containers:
    - name: ubuntu-sleeper
      imagePullPolicy: Never
      image: ubuntu-sleeper
      args: ["10"]
  env:
    - name: APP_COLOR
      value: pink