apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-pod
spec:
  containers:
    - name: ubuntu-sleeper
      imagePullPolicy: Never
      image: ubuntu-sleeper
      args: ["10"]
  envFrom:
    - configMapRef:
        name: app-config